name: M1 Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release (e.g., vM1)"
        required: true
        type: string
      name:
        description: "Release name (defaults to tag if empty)"
        required: false
        type: string
      prerelease:
        description: "Mark as pre-release"
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  build:
    name: Build and Package (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, windows-latest]

    defaults:
      run:
        shell: bash
        working-directory: milestones/m1-hello-javafx

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build + Test + Code Checks
        run: ./gradlew clean spotlessCheck spotbugsMain spotbugsTest test --no-daemon --stacktrace

      - name: Package application (jpackage)
        run: ./gradlew jpackage --no-daemon --stacktrace

      - name: macOS - Zip .app bundle
        if: runner.os == 'macOS'
        run: |
          set -euo pipefail
          cd milestones/m1-hello-javafx/build/jpackage
          APP_DIR=$(ls -d *.app | head -n1)
          echo "Found app: $APP_DIR"
          ditto -c -k --sequesterRsrc --keepParent "$APP_DIR" "${APP_DIR}.zip"
          ls -l

      - name: macOS - Upload zipped .app
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: m1-macos-app
          path: |
            milestones/m1-hello-javafx/build/jpackage/*.app.zip
          if-no-files-found: error

      - name: Windows - Upload .exe installer only
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: m1-windows-exe
          path: |
            milestones/m1-hello-javafx/build/jpackage/*.exe
          if-no-files-found: error

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets

      - name: List downloaded artifacts
        run: |
          echo "Downloaded artifacts:" && ls -R release-assets || true

      - name: Create or update GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.tag }}
          name: ${{ inputs.name || inputs.tag }}
          prerelease: ${{ inputs.prerelease }}
          allowUpdates: true
          replacesArtifacts: true
          artifactErrorsFailBuild: true
          artifacts: |
            release-assets/**/*.zip
            release-assets/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
